api:
  enabled: true

# NOT SUPPORTED FOR http_client source
#acknowledgements:
#  enabled: true

data_dir: ./data

sources:

  http_source:
    type: http_client
    endpoint: ${HTTP_SOURCE_URI}
    headers:
      Accept:
        - text/plain
        - text/html
    method: GET
    scrape_interval_secs: 150
    tls:
      verify_certificate: false

transforms:
  msg_parser:
    type: remap
    inputs: [http_source]
    source: |
      # better to do this check on function level
      # assert_eq!(exists(.file), exists(.message), message: "The required fields are not received")
      
      # https://vector.dev/docs/reference/vrl/functions/#encode_json
      #.=encode_json({"FilePath": .file, "Message": .message})

      # send everything to sinks
      .=.

sinks:

  console_print:
    type: console
    inputs:
      - "msg_parser"
    encoding:
      codec: "json"

  datadog:
    type: datadog_logs
    inputs:
      - "msg_parser"
    compression: gzip
    default_api_key: ${DATADOG_API_KEY}
    # The endpoint to send observability data to
    # endpoint: http://127.0.0.1:8080
    # site: datadoghq.com
    site: datadoghq.eu
